from pptx import Presentation
from pptx.util import Inches, Pt

class PresentationGenerator:
    def __init__(self, data):
        self.data = data
        self.prs = Presentation()
    
    def generate(self, output_path):
        # Title Slide
        slide = self.prs.slides.add_slide(self.prs.slide_layouts[0])
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "Research Paper Summary"
        subtitle.text = "Generated by Autonomous Research Paper Analyzer"
        
        # Core Idea Slide
        self._add_slide("Core Idea", self.data.get("abstract_summary", ""))
        
        # Methodology Slide
        self._add_slide("Methodology", self.data.get("methodology_explained", ""))
        
        # Contributions Slide
        contributions = "\n".join([f"• {c}" for c in self.data.get("key_contributions", [])])
        self._add_slide("Key Contributions", contributions)
        
        # Limitations Slide
        limitations = "\n".join([f"• {l}" for l in self.data.get("limitations", [])])
        self._add_slide("Limitations", limitations)
        
        # Future Work Slide
        improvements = "\n".join([f"• {i}" for i in self.data.get("improvement_suggestions", [])])
        self._add_slide("Future Work & Improvements", improvements)
        
        self.prs.save(output_path)
        return output_path

    def _add_slide(self, title_text, content_text):
        slide = self.prs.slides.add_slide(self.prs.slide_layouts[1])
        title = slide.shapes.title
        content = slide.placeholders[1]
        title.text = title_text
        content.text = content_text
